/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game_npl;
import javax.swing.*;
import java.util.*;
import java.lang.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import java.io.*;
import com.sun.speech.freetts.*;

/**
 *
 * @author COMPUTER MSI
 */
public class UIMAIN extends javax.swing.JFrame {

    /**
     * Creates new form UIMAIN
     */
    public UIMAIN() {
        pack();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jDialog3 = new javax.swing.JDialog();
        jDialog4 = new javax.swing.JDialog();
        popupMenu1 = new java.awt.PopupMenu();
        popupMenu2 = new java.awt.PopupMenu();
        jLabel2 = new javax.swing.JLabel();
        Images = new javax.swing.JLabel();
        OK = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        popupMenu1.setLabel("popupMenu1");

        popupMenu2.setLabel("popupMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Araiwha? version 1.2.1");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game_npl/images/howto.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, -1, -1));

        Images.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game_npl/images/1.png"))); // NOI18N
        getContentPane().add(Images, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 610, 630));

        OK.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        OK.setText("OK/NEXT");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });
        getContentPane().add(OK, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 720, -1, 40));

        jTextField1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 720, 480, 40));

        jButton2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jButton2.setText("Speak");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 370, 150, 390));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, 630, 390));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game_npl/images/Background.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1510, 800));

        getAccessibleContext().setAccessibleName("Araiwha? version 1.1");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int count=0;
    String check = "✖Wrong";
    String [] information ={"!Correct \n\n Information of India \n\n Capital : New Delhi \n\n Currentcy : Indian Rupee \n\n"
            + " Population : 1,353,159,698 \n\n The total land area is 2,973,190 Square kilometer \n\n Landmass : Southern Asia",
              "!Correct \n\n Information of Italy \n\n Capital : Rome \n\n Currentcy : Euro \n\n"
            + " Population : 59,294,708 \n\n The total land area is 294,140 Square kilometer \n\n Landmass : Southern Europe",
              "!Correct \n\n Information of Japan \n\n Capital : Tokyo \n\n Currentcy : Yen \n\n"
            + " Population : 127,201,391 \n\n The total land area is 364,555 Square kilometer \n\n Landmass : Eastern Asia",
            "!Correct \n\n Information of England \n\n Capital : London \n\n Currentcy : Pound \n\n"
            + " Population : 66,550,939 \n\n The total land area is 241,930 Square kilometer \n\n Landmass : Northern Europe",
            "!Correct \n\n Information of France \n\n Capital : Paris \n\n Currentcy : Euro \n\n"
            + " Population : 65,218,903 \n\n The total land area is 547,557 Square kilometer \n\n Landmass : Western Europe",
              "!Correct \n\n Information of Thailand \n\n Capital : Bangkok \n\n Currentcy : Baht \n\n"
            + " Population : 69,175,047 \n\n The total land area is 510,890 Square kilometer \n\n Landmass : South-Eastern Asia",
              "\nTHE END \n 6/6 Point \n\n Credits \n B5804238 \n B5804566 \n B5805808 \n B5814985 \n B5824366 \n\n THANK YOU & ENJOY"};
    String [] p = {"[Ii][n][d][i][a]","[Ii][t][a][l][y]","[Jj][a][p][a][n]","[Ee][n][g][l][a][n][d]","[Ff][r][a][n][c][e]","[Tt][h][a][i][l][a][n][d]",""};
    String [] imagesgame = {"1.png","2.png","3.png","4.png","5.png","6.png","7_1.gif"};
    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        
        ImageIcon[] imagelist = new ImageIcon[7];
        for(int i=0;i<imagelist.length;i++) {
        imagelist[i] = new ImageIcon(getClass().getResource("/game_npl/images/"+imagesgame[i]));
        }
 
        if(count>=0 && count<imagesgame.length) {
        Images.setIcon(imagelist[count]);
        
        Pattern pattern=Pattern.compile(p[count]);
        Matcher regMatcher = pattern.matcher(jTextField1.getText());
        jTextArea1.setText("");
            if(regMatcher.matches()) {
                count++;
                jTextField1.setText("");
                jTextArea1.setText(information[count-1]);
            }
            else {count=count;
                jTextField1.setText("");
                //jTextArea1.setText(check);
             }
        }
    }//GEN-LAST:event_OKActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed
    private static final String VOICENAME="kevin16";
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // speak:
        Voice voice;
        VoiceManager vm= VoiceManager.getInstance();
        voice=vm.getVoice(VOICENAME);
        
       voice.allocate();
       
       try{
           voice.speak(jTextArea1.getText());
       }catch(Exception e){}
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIMAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIMAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIMAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIMAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIMAIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Images;
    private javax.swing.JButton OK;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JDialog jDialog4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    // End of variables declaration//GEN-END:variables

}
